{{- $name := include "svc.fullname" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}
  labels:
    app: {{ template "svc.name" .}}
    chart: {{ template "svc.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    releaseNo: {{ .Values.releaseNo }}
data:
  _DataConfig__EmailConfig__URI: https://emailsender.com/
  _DataConfig__EmailConfig__RelativeApiPath: api/Office/SendMail



